// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApazOeJpS7YBMS_S7V7t3VekI2nxgIQ1k',
    appId: '1:660991473775:web:d3cc8a4ff532f39d77759a',
    messagingSenderId: '660991473775',
    projectId: 'actividad3-159ca',
    authDomain: 'actividad3-159ca.firebaseapp.com',
    storageBucket: 'actividad3-159ca.firebasestorage.app',
    measurementId: 'G-6Y1BJPPTQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPL0afK8NfamncjIAkrz_aLEpoNVp-xqE',
    appId: '1:660991473775:android:f2b3509bd410532977759a',
    messagingSenderId: '660991473775',
    projectId: 'actividad3-159ca',
    storageBucket: 'actividad3-159ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmeeWQ3XZZLpSISWRlxbNkunLzge79sS8',
    appId: '1:660991473775:ios:93e99779aa78bbc177759a',
    messagingSenderId: '660991473775',
    projectId: 'actividad3-159ca',
    storageBucket: 'actividad3-159ca.firebasestorage.app',
    iosBundleId: 'com.example.pruebafirebase',
  );
}
